### ISSUE TITLE
Update to latest libphonenumber

### ISSUE THREAD

**Issue by aeischeid** [ataylor284/grails-phonenumbers#4]
Looks like a pretty good plugin, just giving it a try. Noticed the version is a little behind latest which is 7.0.2 for libphonenumber and 2.19 for geocoder

**Comment by steffimueller** [comment]
+1

**Comment by confile** [comment]
+1 @ataylor284 Could you please update the plugin?

**Comment by ataylor284** [comment]
Done!  Sorry for leaving it for so long.

**Comment by confile** [comment]
@ataylor284 Thank you!
